# Generated by Django 2.2 on 2020-02-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefedditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeddITem',
            new_name='ProfileFeedItem',
        ),
    ]
